# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gophersay < Formula
  desc ""
  homepage "https://github.com/seedpower/homebrew-apps"
  version "1.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seedpower/xproduct/releases/download/v1.0.9/xproduct_1.0.9_darwin_amd64.tar.gz"
      sha256 "4d5c093839acec43d0b945d993d1131b3b674272c2ab3e693edf8bf21b69c10e"

      def install
        bin.install "xproduct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seedpower/xproduct/releases/download/v1.0.9/xproduct_1.0.9_darwin_arm64.tar.gz"
      sha256 "744c3c29cbda4a544641ef7d5e81c545b7fc0efd6bcfcc36cbb59dfb5c3edf32"

      def install
        bin.install "xproduct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/seedpower/xproduct/releases/download/v1.0.9/xproduct_1.0.9_linux_amd64.tar.gz"
        sha256 "7de1087213bc4ac042942fc5525c000cd3b971015da6016d502078d2dfccce17"

        def install
          bin.install "xproduct"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/seedpower/xproduct/releases/download/v1.0.9/xproduct_1.0.9_linux_arm64.tar.gz"
        sha256 "840ccabf57b8c9a0a014d70089700371b54fbd4419470f2d23e8ae2b7efc44a9"

        def install
          bin.install "xproduct"
        end
      end
    end
  end
end
