# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xproduct < Formula
  desc ""
  homepage "https://github.com/seedpower/xproduct"
  version "1.0.10"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/seedpower/xproduct/releases/download/v1.0.10/xproduct_1.0.10_darwin_amd64.tar.gz"
    sha256 "edc2df935c13a203fe449c83797ae7eb368b73d92f022fca4cd28d9a079d5699"

    def install
      bin.install "xproduct"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/seedpower/xproduct/releases/download/v1.0.10/xproduct_1.0.10_darwin_arm64.tar.gz"
    sha256 "98c8c1afb12dacba1a398959b7f3eebfb635757265db22e0c5cb868f875fb251"

    def install
      bin.install "xproduct"
    end
  end
end
