# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xproduct < Formula
  desc ""
  homepage "https://github.com/seedpower/xproduct"
  version "1.0.17"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/seedpower/xproduct/releases/download/v1.0.17/xproduct_1.0.17_darwin_amd64.tar.gz"
    sha256 "cb024acc0f1366912db23d40b1bc213eede3b58c4c56b0253d69cc8862a777c5"

    def install
      bin.install "xproduct"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/seedpower/xproduct/releases/download/v1.0.17/xproduct_1.0.17_darwin_arm64.tar.gz"
    sha256 "e33e2fecd08dada3cc430f3e5ee6f646f45beb77614d6bac6dbd01f8c971a113"

    def install
      bin.install "xproduct"
    end
  end

  def post_install
    ohai "To start the service, run: brew services start #{name}"
  end

  service do
    run [opt_bin/"xproduct"]
    environment_variables MYAPP_ENVIRONMENT: "production"
    keep_alive true
    error_log_path var/"log/xproduct.log"
    log_path var/"log/xproduct.log"
    working_dir var
  end
end
